# Generated by Django 5.1.1 on 2024-09-28 15:38

import products.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_description_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/images/",
                validators=[products.validators.validate_file_size],
            ),
        ),
    ]
